import puppeteer from 'puppeteer-core';
const out = process.argv[2];
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new' });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto('http://localhost:8765/', { waitUntil: 'networkidle0' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle0' });
await page.waitForFunction(() => document.querySelector('#status-valid .label').textContent.includes('TEI'));
await page.click('[data-tab=preview]');
const sleep = ms => new Promise(r => setTimeout(r, ms));
const info = () => page.evaluate(() => {
  const raw = document.querySelector('#preview-raw'); const d = document.querySelector('#preview-frame').contentDocument; const b = document.querySelector('#preview-banner');
  const l = d && d.getElementsByTagName('l')[0];
  return { raw: raw.hidden ? 'hidden' : 'shown', banner: b.hidden ? null : b.innerText.replace(/\s+/g, ' '), lDisplay: l ? getComputedStyle(l).display : 'none', body: d && d.body ? d.body.innerText.slice(0, 60).replace(/\s+/g, ' ') : '' };
});
await sleep(1200);
console.log('1. empty template (no link):', await info());
await page.screenshot({ path: out + '/pv-nolink.png' });
await page.evaluate(() => { const v = window.teiEditor; const t = v.state.doc.toString(); const i = t.indexOf('<TEI'); v.dispatch({ changes: { from: i, insert: '<?xml-stylesheet type="text/css" href="visualise.css"?>\n' } }); });
await sleep(1200);
console.log('2. wrong name:', await info());
await page.evaluate(() => { const v = window.teiEditor; const t = v.state.doc.toString(); const i = t.indexOf('<?xml-stylesheet'); const j = t.indexOf('?>', i) + 3; v.dispatch({ changes: { from: i, to: j } }); });
await sleep(1200);
await page.click('#preview-banner button');
await sleep(1200);
console.log('3. after "Add it for me":', await info(), 'line:', await page.evaluate(() => { const v = window.teiEditor; return v.state.doc.lineAt(v.state.selection.main.head).text; }));
await page.screenshot({ path: out + '/pv-linked.png' });
console.log('errors', errs);
await browser.close();
